export const TRANSACTION_TYPES = ['IN', 'OUT'] as const;

export const CURRENCY_CODES = ['USD', 'EUR', 'RUB', 'BYN'] as const;

export const DATE_INPUT_FORMAT = 'YYYY-MM-DD';

export const DATETIME_INPUT_FORMAT = 'YYYY-MM-DDTHH:mm';

export const PRESET_CATEGORIES = [
  {
    'transaction_type': 'OUT',
    'name': 'Food & Drink',
    'display_order': 1,
    'icon': 'Utensils',
    'color': '#3cff00',
    'subcategories': [
      {
        'transaction_type': 'OUT',
        'name': 'Groceries',
        'display_order': 1,
        'icon': 'ShoppingBasket',
        'color': '#3cff00',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Cafes & Restaurants',
        'display_order': 2,
        'icon': 'UtensilsCrossed',
        'color': '#3cff00',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Alcohol',
        'display_order': 3,
        'icon': 'Martini',
        'color': '#3cff00',
        'subcategories': [],
        'transactions': [],
      },
    ],
    'transactions': [],
  },
  {
    'transaction_type': 'OUT',
    'name': 'Transportation',
    'display_order': 2,
    'icon': 'Tractor',
    'color': '#ffea00',
    'subcategories': [
      {
        'transaction_type': 'OUT',
        'name': 'Public Transit',
        'display_order': 1,
        'icon': 'BusFront',
        'color': '#ffea00',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Taxi & Ride-Sharing Services',
        'display_order': 2,
        'icon': 'CarTaxiFront',
        'color': '#ffea00',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Airline Tickets',
        'display_order': 3,
        'icon': 'Plane',
        'color': '#ffea00',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Car Payments',
        'display_order': 4,
        'icon': 'Car',
        'color': '#ffea00',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Gas & Fuel',
        'display_order': 5,
        'icon': 'Fuel',
        'color': '#ffea00',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Parking & Tolls',
        'display_order': 6,
        'icon': 'ParkingSquare',
        'color': '#ffea00',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Cycling',
        'display_order': 7,
        'icon': 'Bike',
        'color': '#ffea00',
        'subcategories': [],
        'transactions': [],
      },
    ],
    'transactions': [],
  },
  {
    'transaction_type': 'OUT',
    'name': 'Housing & Houseware',
    'display_order': 3,
    'icon': 'Home',
    'color': '#ff6f00',
    'subcategories': [
      {
        'transaction_type': 'OUT',
        'name': 'Rent & Mortgage',
        'display_order': 1,
        'icon': 'Receipt',
        'color': '#ff6f00',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Repairs & Maintenance',
        'display_order': 2,
        'icon': 'Wrench',
        'color': '#ff6f00',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Utilities',
        'display_order': 3,
        'icon': 'Droplets',
        'color': '#ff6f00',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Furniture & Appliances',
        'display_order': 4,
        'icon': 'Lamp',
        'color': '#ff6f00',
        'subcategories': [],
        'transactions': [],
      },
    ],
    'transactions': [],
  },
  {
    'transaction_type': 'OUT',
    'name': 'Entertainment',
    'display_order': 4,
    'icon': 'Clapperboard',
    'color': '#ff0090',
    'subcategories': [
      {
        'transaction_type': 'OUT',
        'name': 'Movies & Shows',
        'display_order': 1,
        'icon': 'Film',
        'color': '#ff0090',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Music & Concerts',
        'display_order': 2,
        'icon': 'Music',
        'color': '#ff0090',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Sports & Recreation',
        'display_order': 3,
        'icon': 'Trophy',
        'color': '#ff0090',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Hobbies & Crafts',
        'display_order': 4,
        'icon': 'ScissorsSquare',
        'color': '#ff0090',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Book & Magazines',
        'display_order': 5,
        'icon': 'Newspaper',
        'color': '#ff0090',
        'subcategories': [],
        'transactions': [],
      },
    ],
    'transactions': [],
  },
  {
    'transaction_type': 'OUT',
    'name': 'Clothing & Appearence',
    'display_order': 5,
    'icon': 'Shirt',
    'color': '#4400ff',
    'subcategories': [
      {
        'transaction_type': 'OUT',
        'name': 'Clothing & Accessories',
        'display_order': 1,
        'icon': 'Shirt',
        'color': '#4400ff',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Haircuts & Styling',
        'display_order': 2,
        'icon': 'Scissors',
        'color': '#4400ff',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Hygiene & Cosmetic',
        'display_order': 3,
        'icon': 'SprayCan',
        'color': '#4400ff',
        'subcategories': [],
        'transactions': [],
      },
    ],
    'transactions': [],
  },
  {
    'transaction_type': 'OUT',
    'name': 'Education & Studying',
    'display_order': 6,
    'icon': 'GraduationCap',
    'color': '#00ffcc',
    'subcategories': [
      {
        'transaction_type': 'OUT',
        'name': 'Books',
        'display_order': 1,
        'icon': 'BookOpen',
        'color': '#00ffcc',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Tuition & Fees',
        'display_order': 2,
        'icon': 'School',
        'color': '#00ffcc',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Certification & Examination',
        'display_order': 3,
        'icon': 'FileBadge',
        'color': '#00ffcc',
        'subcategories': [],
        'transactions': [],
      },
    ],
    'transactions': [],
  },
  {
    'transaction_type': 'OUT',
    'name': 'Devices & Internet',
    'display_order': 7,
    'icon': 'MonitorSmartphone',
    'color': '#00a2ff',
    'subcategories': [
      {
        'transaction_type': 'OUT',
        'name': 'Devices',
        'display_order': 1,
        'icon': 'Calculator',
        'color': '#00a2ff',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Software & Subscriptions',
        'display_order': 2,
        'icon': 'MonitorPlay',
        'color': '#00a2ff',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Internet Bill',
        'display_order': 3,
        'icon': 'Router',
        'color': '#00a2ff',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Telephone Bill',
        'display_order': 4,
        'icon': 'PhoneCall',
        'color': '#00a2ff',
        'subcategories': [],
        'transactions': [],
      },
    ],
    'transactions': [],
  },
  {
    'transaction_type': 'OUT',
    'name': 'Healthcare',
    'display_order': 8,
    'icon': 'HeartPulse',
    'color': '#ff0000',
    'subcategories': [
      {
        'transaction_type': 'OUT',
        'name': 'Gym & Fitness',
        'display_order': 1,
        'icon': 'Dumbbell',
        'color': '#ff0000',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Medications',
        'display_order': 2,
        'icon': 'Pill',
        'color': '#ff0000',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Diagnosis & Treatment',
        'display_order': 3,
        'icon': 'Stethoscope',
        'color': '#ff0000',
        'subcategories': [],
        'transactions': [],
      },
    ],
    'transactions': [],
  },
  {
    'transaction_type': 'OUT',
    'name': 'Gifts & Donations',
    'display_order': 9,
    'icon': 'Gift',
    'color': '#8800ff',
    'subcategories': [
      {
        'transaction_type': 'OUT',
        'name': 'Gifts',
        'display_order': 1,
        'icon': 'Gift',
        'color': '#8800ff',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Donations',
        'display_order': 2,
        'icon': 'Coins',
        'color': '#8800ff',
        'subcategories': [],
        'transactions': [],
      },
    ],
    'transactions': [],
  },
  {
    'transaction_type': 'OUT',
    'name': 'Finance & Insurance',
    'display_order': 10,
    'icon': 'Landmark',
    'color': '#ffb300',
    'subcategories': [
      {
        'transaction_type': 'OUT',
        'name': 'Taxes',
        'display_order': 1,
        'icon': 'BadgePercent',
        'color': '#ffb300',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Insurance',
        'display_order': 2,
        'icon': 'Banknote',
        'color': '#ffb300',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Investments',
        'display_order': 3,
        'icon': 'PiggyBank',
        'color': '#ffb300',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'OUT',
        'name': 'Compensations & Fines',
        'display_order': 4,
        'icon': 'Scale',
        'color': '#ffb300',
        'subcategories': [],
        'transactions': [],
      },
    ],
    'transactions': [],
  },
  {
    'transaction_type': 'OUT',
    'name': 'Miscellaneous',
    'display_order': 11,
    'icon': 'HelpCircle',
    'color': '#777777',
    'subcategories': [],
    'transactions': [],
  },
  {
    'transaction_type': 'IN',
    'name': 'Occupational Earnings',
    'display_order': 1,
    'icon': 'Briefcase',
    'color': '#00b7ff',
    'subcategories': [
      {
        'transaction_type': 'IN',
        'name': 'Salary',
        'display_order': 1,
        'icon': 'Wallet2',
        'color': '#00b7ff',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'IN',
        'name': 'Side Job',
        'display_order': 2,
        'icon': 'Building2',
        'color': '#00b7ff',
        'subcategories': [],
        'transactions': [],
      },
      {
        'transaction_type': 'IN',
        'name': 'Business',
        'display_order': 2,
        'icon': 'Bitcoin',
        'color': '#00b7ff',
        'subcategories': [],
        'transactions': [],
      },
    ],
    'transactions': [],
  },
  {
    'transaction_type': 'IN',
    'name': 'Investments',
    'display_order': 2,
    'icon': 'Percent',
    'color': '#00ff40',
    'subcategories': [],
    'transactions': [],
  },
  {
    'transaction_type': 'IN',
    'name': 'Gifts',
    'display_order': 3,
    'icon': 'Gift',
    'color': '#ff001e',
    'subcategories': [],
    'transactions': [],
  },
  {
    'transaction_type': 'IN',
    'name': 'Miscellaneous',
    'display_order': 4,
    'icon': 'HelpCircle',
    'color': '#777777',
    'subcategories': [],
    'transactions': [],
  },
];